frk_working_dir = "/CFRK_pkg"

cfrk_package_dir = paste0(frk_working_dir, '/')
output_main_dir = paste0(frk_working_dir, "/example output/example_CFRK/")

data_dir <- paste0(current_dir, '../data/')

folder_data_nord = "/Data-Nord"
shapefile_comuni_filepath = paste0(folder_data_nord, '/Com01012024_WGS84.shp')